version: '3.1'
services:
    db:
      image: mysql
      environment:
        MYSQL_ROOT_PASSWORD: 'root'
        MYSQL_PASSWORD: 'root'
        MYSQL_ALLOW_EMPTY_PASSWORD: 'no'
      ports:
        - 3306:3306